// =============================================================================
// File    : BaggageResponseDto.cs
// Layer   : TECAir.Core → DTOs
// Purpose : Defines request and response payloads used by the application.
// =============================================================================

namespace TECAir.Core.DTOs.Baggage
{
    public class BaggageResponseDto
    {
        // Unique identifier generated by the database.
        public int BaggageId { get; set; }
        public decimal Weight { get; set; }
        public string Color { get; set; } = string.Empty;
        public string ReservationCode { get; set; } = string.Empty;

        // Full name of the passenger owner (resolved from reservation → user).
        public string PassengerName { get; set; } = string.Empty;

        // Position of this baggage item for the passenger (1st, 2nd, 3rd…).
        public int BaggagePosition { get; set; }

        // Additional charge applies only to this baggage item according to the stated tariff.
        public decimal ExtraChargeForThisBag { get; set; }

        // Suma acumulada de todos los cargos adicionales del pasajero
        public decimal TotalExtraCharge { get; set; }
    }
}
